### ISSUE TITLE
clipped pulse warning possibly not working

### ISSUE THREAD

**Issue by eauerbach** [CMRR-C2P/MB#103]
Reported that the clipped RF pulse warning is not working on R012b on VD13D.

**Comment by halfSpinDoctor** [comment]
I can confirm that I have seen this behaviour on our VD13D Prisma (mbep2d_bold). Sometimes the 'clipped RF pulse' warning will come up, but sometimes no warning will appear even though the transmit voltage of MBExc 1H is maxed out.

I have confirmed that increasing the excitation pulse width above a certain threshold will decrease the transmit voltage below the maximum value, and doing so will result in an increase in image SNR [below for GM ROI], presumably by exciting at proper Ernst angle instead of under-flipping:

I am happy to do follow-up testing if you need any additional information.

![screen shot 2015-10-13 at 1 25 50 pm](https://cloud.githubusercontent.com/assets/10052197/10454628/f82f3dd0-71ad-11e5-952c-c86a81591661.png)


![image](https://cloud.githubusercontent.com/assets/10052197/10454605/b5f98b5a-71ad-11e5-9762-cde7b13fef70.png)

![tsnr_mb_pw](https://cloud.githubusercontent.com/assets/10052197/10454623/e556ce9e-71ad-11e5-81a5-1ccfca02512d.png)

**Comment by eauerbach** [comment]
Confirmed this is not working as intended on VD13D.

**Comment by eauerbach** [comment]
Fixed in R012d/R013.
