### ISSUE TITLE
Reconstruction errors on Tim Trio

### ISSUE THREAD

**Issue by dcbrien** [CMRR-C2P/MB#107]
Release 012b
18 May 2015

We are getting image reconstruction errors intermittently on our Tim Trio 3T system (VB19A).  We are attempting multiple 2mm ISO BOLD sequences. 

The errors read:

_Connection to Image Reconstruction System has been lost.
Image Calculation error.  Retry, reboot syngo MR, etc...
Image Reconstruction Failed, MeasUiD   277._

All images collected after this are lost.  Because of the long lag between acquisition and reconstruction on our system, we lost half an hour of data after this because it seems like the system dropped all images after that point.

I will contact Siemens about this as well.  Let me know what other details you need.

Is it possibly for us to attempt the remote reconstruction or, if not possible, could we get software for post-scan session reconstruction offline?

**Comment by eauerbach** [comment]
I suspect you need a new imager (likely a hardware problem is causing a crash or reboot). Do you have the new "Step5" imager? Otherwise you can send me a savelog and I can have a look at it.

**Comment by dcbrien** [comment]
we had another crash.  can I send you the savelog?

**Comment by eauerbach** [comment]
Sure, you can use this link:
https://www.dropbox.com/request/rF20BOY3GCNt6iaYMACi

**Comment by h-you-man** [comment]
Hey there!
Is there any solutions of this problem? I have the same one on Verio 3T with VB17A.
Is that really due to weak hardware of IRS? 

Siemens says: "We will not support customer sequences. If you want, you can get a new Imager for troubleshooting, but it’s not a guarantee"

Thank you in advance!

**Comment by dcbrien** [comment]
Can we possibly try the remote or offline reconstruction?  We have not found an acceptable solution to this problem on the trio.  We just tried delaying the reconstruction using twix, but that didn't help.  The reconstruction still crashes on the console.  Is there offline code I can install to attempt reconstruction after the fact, maybe in a virtual linux box?

**Comment by eauerbach** [comment]
Sorry for the delay. I looked over the logs and your imager is very clearly running out of memory. Unfortunately you seem to have a lower-end Step4 imager with only 16 GB total RAM, which is not sufficient for the rather demanding sequences you are trying to run. Upgrading the imager hardware is the only solution as far as I can see.

Since you have a VB19A system, if you have a service contract with "Evolve", then you should be eligible for the upgraded "Step5" imager which is a substantial improvement in every way. That would be the best option by far.

Otherwise, the next easiest solution would be to replace your very old Step4 with a slightly better one with 32 GB RAM. That should stop the crashing, but the recon would still be slow. Service may do this automatically if you can convince them to do a replacement (at some point the very old ones will disappear from spare parts inventory), but failing that they might be able to find you a surplus one. When they do Step5 upgrades, the Step4 imagers are disposed of...

Finally, if you are willing and able to modify the imager hardware (generally not ok on a clinical system), then you could consider remote recon and/or installing a memory upgrade yourself. I can provide some basic documentation for this, but you are on your own to sort out the details with your local IT and Siemens service people.

**Comment by jpyles** [comment]
We are also having this problem on a Verio 3T with VB17A. 

Errors are: "Scanning stopped by Image Reconstruction." "Image reconstruction failed."

This is happening on a 2mm isovoxel multiband factor 3 scan with a 106 matrix at 2000ms TR. The error stops the scanning of the current run, although reconstruction actually seems to proceed until the last image acquired. A similar scan with a smaller 96 matrix recons in real-time and does not seem to produce the errors (the 106 matrix scan has a recon lag).

This error also has happened during an off the shelf Siemens EPI BOLD sequence if it was scanned after a multiband sequence.

We are in contact with Siemens but they have been unable to solve the problem. Our imager was replaced, as were interface cards. The imager is a Step4 with only 16GB of RAM. However looking at the log file (if I'm reading it correctly), it doesn't seem to be running out of memory, but I could be wrong about this. The host is an older Fujitsu Celsius R650.

Any suggestions? I'm happy to send along the log file info if that would be helpful. We are essentially halted from starting new studied until we can figure this out.

Many thanks in advance!
