### ISSUE TITLE
R013A from R012c: DTI protocol not properlly converted

### ISSUE THREAD

**Issue by costintanase** [CMRR-C2P/MB#109]
On a TimTrio, VB17:
 
I have a working, R012c DTI protocol based on the cmrr sequence. 

After  I upgraded to R013A, the moment I open the DTI in the Protocol Explorer, and/or I drag it to be run, I get a pop up window: 'protocol has been fixed' 

Unfortunately:  the DTI sequence is replaced with an ep2d_bold (as far as I can tell), the 32ch coil is changed to BC, the DTI tab is gone. 

I did not seem to have any problems with the bold when going from 12c to 13a. 

Thanks!

**Comment by rjgenik** [comment]
I just installed on Verio VB17A. Exact same thing happened: when I "view" the protocol, it appears that the ep2d protocol cards are being shown (there is no diffusion card), the sequence name is blank in the upper right corner, and the hover comment is the the sequence is multiband diffusion one (forgot to write name down at scanner), but there is no variant shown. When I open the protocol and it becomes "fixed", the diffusion cards are shown, but all of the data has been reset to original default values. 

This is similar to what happens when you have a mismatch between the DiffusionVectors.txt file number of directions and the number of directions in a "Free" protocol (e.g. trying to run with the wrong directions file -- you want it to crash in that case, and it does.)

**Comment by eauerbach** [comment]
Is this only happening for existing protocols using "Free" mode vector sets?

**Comment by costintanase** [comment]
My protocols use the Free mode, only. If that helps, i could try creating/converting other protocols.

In particular, this protocol, on our Trio, worked only after I upgraded to R012c

**Comment by romainVala** [comment]
Dear All

I just notice the same bug on Verio VB17 : losing all parameter. If I open the protocol from the protocol editing windows.

I find a quick solution : If I take an old exam (done before the upgrade) and I drag and drop it in the protocol definition windows. then it convert the protocol but keep all parameter ok I get notification for 2 changes : 
echo spacing 0 -> 0.7
diffusion sheme  -> monopolar

I do not remember what was the echo spacing before, but I am sure I already was using monopolar.
may be the parameter definition change place ?

PS for me also I am always using free direction

Many thanks 

Romain

**Comment by rjgenik** [comment]
All of our DTI protocols are Free as well. 
We have scans this weekend and no update available so I'll try and recreate the scan protocols from the "fixed" version or from Insert Sequence as a work-around. I'll report back if this works.

Sincerely,
Rich

**Comment by eauerbach** [comment]
Ok, sorry, it turns out there is a bug in R013 that is preventing the correct diffusion **scheme** (e.g. _Bipolar_, _Monopolar_) from being read from existing protocols. The diffusion **mode** (e.g. _MDDW_, _Free_) doesn't matter. This affects the VB17A/VB19A/VB20P versions of the diffusion sequence only.

R013a will be up on the web site soon which corrects this. If you want to save time when updating, you can just copy the cmrr_mbep2d_diff.* sequence binaries to %CustomerSeq% and skip the installer.

**Comment by rjgenik** [comment]
Hi Eddie,

Thanks! This saves me several hours effort later tonight.

Cheers,

Rich

**Comment by vkemper** [comment]
Thanks for the quick solution, Eddie! 
I guess I'm too late to the party, but perhaps for future reference: It is possible to restore the old protocols by inserting a new protocol of the diffusion sequence, and using the copying option in the properties section of the protocol. By copying "everything" from the original protocol in the protocol browser and then unlinking the two protocols again, one could create a protocol that would not be "fixed" by the scanner. Just found this out earlier today before seeing the new version.
cheers
valentin

**Comment by costintanase** [comment]
Thank you!
The new R13a works with no issues! 

Best Regards, 
Costin
