### ISSUE TITLE
VB17 problem with phase image recon

### ISSUE THREAD

**Issue by whitecraine** [CMRR-C2P/MB#114]
In comparing with the siemens stock images, I've noticed that the phase images are extremely noisy and unstable. It's possible that this problem has been there since very early on and may also impact GRE sequences as well. Please look into this as this will impact our ability to do QSM or SWI type processing. 

I’ve tried everything I could think of (turned off ipat/MB, SENSE1, retro recons with different options) however nothing really impacts this faulty phase recon. 

For comparison of image quality, I've uploaded a few TRs from stock and c2p sequences here. 
https://www.dropbox.com/sh/f1y26edv1hruncu/AAC3DCn458kMHyqXMVny7Fc6a?dl=0

**Comment by eauerbach** [comment]
How are you doing the phase recon with the product sequences, since phase recon is not supported by the product? If you are forcing it in retro recon, depending on how you do it there are some buggy interactions with the Maxwell correction functor in the product ICE that I work around in the MB ICE.

IIRC if you do a phase-only retro reconstruction, the bugged product ICE will run the Maxwell correction (which is an image-space correction only designed to run on magnitude images) on the phase images. If you do a magnitude+phase recon, it not only runs the Maxwell reconstruction on the phase images where it shouldn't, it skips it for the magnitude images where it should. You have to disable the Maxwell correction explicitly (YAPS.ucMaxwellCorrection) for both your magnitude and phase recons (or a single magnitude+phase recon) if you want to get magnitude images and valid phase images with the same distortions.

**Comment by whitecraine** [comment]
I enabled the phase/magnitude recon option in the stock pulse sequence back when I was in grad school. I believe we also disabled the Maxwell correction for the phase at that time when I found out that the phase images were being linearly interpolated (and thus impossible to spatially unwrap properly). 

That said, would you agree that the phase images in the C2P are unusually noisy/unstable (even relative to the corresponding magnitude image)? 

If it helps, I have some scan time tomorrow where I can test with/without Maxwell correction and see if it affects the noise performance of the stock sequence. I’ll also compare using the GRE sequence, so we have a better direct comparison.

**Comment by whitecraine** [comment]
I checked the raw data from the modified stock sequence I was using and the ucMaxwellCorrection parameter was zero. Retroreon with it set to 1 changed the distortions but the noise level remained the same. 

I also ran the stock gre (3D mode, 2mm iso, 50-100ms TR) and it looked similarly noisy. However in 2D mode (1000ms TR; which is closer to what the fieldmap protocol uses) the phase images did not appear noisy. Let me know if I can provide more info to help.

**Comment by eauerbach** [comment]
I will look at it if I have a chance. I think the basic issue is that the phase recon does not do anything to account for inter-coil phase differences; it straight up sums complex multi-coil data prior to calculating the phase, so you can expect to get bad results. Why it looks good in some cases but not others, I don't know.

For EPI, thinking about it, perhaps the phase (ghost) correction has something to do with it. The MB sequences have been updated to use what we consider to be the most stable Siemens phase correction, which fits the phase difference between the odd and even lines, correcting one and leaving the other untouched. The VB17A product sequences used the older correction which removes the phase from both the odd and even lines. That turns out to be less stable for ghost correction (resulting in what Siemens calls the "disco" artifact where the correction fails completely for some repetitions), but maybe it is correcting the inter-coil phase for you. Later with VB17A-SP4 the product diffusion switched to the new correction, and by VD13A I think all of the sequences are using the new correction. But the VB17A product BOLD sequence I think is still using the old correction. You can change this mode with YAPS.iOnlinePhaseCorrectionAlgo = 68 (new) and 7 (old).

In the long run I think the best thing is to do an intelligent phased coil combination prior to the phase calculation. There are many papers on this...if you have a technique in mind that is relatively simple and stable I could implement it in the ICE recon.

**Comment by whitecraine** [comment]
Thanks for the help! I checked the phaseCorrectionAlgo and it is set to 7
for  both sequences tested. I tried changing it to 68 but it did not make a
significant difference in the resultant quality of phase images in the two
sequences. I'll compare the raw file headers more carefully to see if there
are any other parameters that differ.

**Comment by whitecraine** [comment]
Thanks for the help! While initial tests at the Berkeley Trio seemed to show no effect (I'll have to try again later), I managed to bring the data to the 7T VA where the phaseCorrectionAlgo did appear to make all the difference. When set to 7 (the default) the phase images look clean, however when set to 68, the phase images have more wrapping, noise, and instability. Unfortunately, I wasn't able to check the C2P retorecon at the 7T since we haven't installed the latest version yet. Let me know if I can provide more info to help. Next change I'll get, I'll do some BOLD contrast comparisons with the various phase correction algorithms with stock and C2P sequences.

**Comment by whitecraine** [comment]
Tested again on the Berkeley Trio and for some reason, there was still no effect on the resultant phase images when changing the onlinePhaseAlgo parameter from 7 to 68. The stock phase images were still clean (regardless of 7 and 68) and the C2P was still noisy regardless. This suggests to me that the 68 option might not be available on the Trio for stock BOLD (even though is says SP4 is installed). Weird right? Should I contact my local Siemens specialist?

Is it possible the C2P is also "locked" in terms of using 68 on the Trio? Oddly, the onlinePhaseCorrectionAlgo reads 7 when I load in the raw data in twix.

**Comment by whitecraine** [comment]
Digging a litte deeper, I found out I could check which algorithms correspond to which parameters by opening the twix and viewing "onlinetse" under the "PIPE". 

For the stock sequence, setting "onlinePhaseCorrAlgo" to the following:
1: IsOnlinePCCCrossCorr
2: IsOnlinePCAutoCorr
4: IsOnlinePCPrimaryMode
8: IsOnlinePCCrossCorrAcrossSegments
16: IsOnlinePCFiltered
32: IsOnlinePCCrossCorrAcrossSegmentsEPI

Summing any of these together enables those algorithms (e.g. 7: CrossCorr, AutoCorr & Primary Mode). Wish I knew what "Primary Mode" as well as the other modes were!

Troubling however is that for the C2P, none of these options were available (at least not on our Trio). Setting onlinePhaseCorrAlgo to 1,2,8,16,32, or 64 all resulted in raid connection being broken. Oddly both 4 and 7 did exactly the same thing (PrimaryMode + AutoCrossCorrAcrossSegments).

I'll try these again at the 7T - hopefully on Monday.

**Comment by whitecraine** [comment]
Found out from my local siemens contact that a likely reason why 68 is working for the stock fMRI sequence on our 7T but not the Trio is because a Siemens WIP is installed on the 7T (so IsOnlinePCAutoCorssCorrAcrossSegments is available as 64 even without onlinetse_advanced being explicitly listed in the PIPE).

**Comment by eauerbach** [comment]
Maybe, or it could be the 7T feature patch which updates the default onlinetse functor to the latest version. On Trio, the new options are only available if the default onlinetse is explicitly replaced with onlinetse_advanced, which only the product diffusion sequence does, as do my C2P sequences. Since for the C2P this replacement and reconfiguration is hard-coded in the configurator, changing the flags in twix has no effect.

**Comment by pfannmoe** [comment]
Dear all,

I am just setting up the multiband sequence on Siemens Verio 3T with VB17A and would like to use the sequence for gradient echo BOLD-fMRI. The voxel size is 1.5 mm isotropic and magnitude/phase reconstruction is set in the protocol. 

The phase reconstruction needs to be carried out with care, as I noted from the above issues. Currently, I feel a bit lost. Could you tell me the most important options that I have to care about? As far as I understood the Maxwell correction needs to be disableb the explicitly in the protocol. The other points in the discussion above could also be important for the Verio. Can you give me a hind?

Yours pfannmoe

**Comment by whitecraine** [comment]
Hi pfannmoe, unfortunately the phase correction algorithm is still hard coded for this sequence. Until this is corrected, the phase data will not be particularly useful. Until this is resolved, unfortunately, you may have to revert to the Siemens ep2d_bold sequence if you are in need of proper phase EPI images.

**Comment by pfannmoe** [comment]
Good to know! Thank you very much.

**Comment by eauerbach** [comment]
For R016, I have rearranged the SENSE1 pipeline such that it will now output phase corrected images; this is my proposed solution to this issue which should work on all platforms.
