### ISSUE TITLE
VD13D Multiband sequence failure to SBFakeSliceBands

### ISSUE THREAD

**Issue by mix1007** [CMRR-C2P/MB#115]
I have created a configuration file called “MBAdvancedSettings.ini” with the two lines and place that it in C:\MedCom\MriCustomer\seq

[MultiBand]
SBFakeSliceBands = 1

 But I can not find the Fake MB factor for SB* on the Sequence, Special tab. 

Thank you for your help

**Comment by dilaraerisen** [comment]
Hi,

I'm having the same problem. Is there a fix for this?

**Comment by mix1007** [comment]
Here is response from Essa

On Wed, Apr 6, 2016 at 11:04 AM, Essa Yacoub <yaco0006@umn.edu<mailto:yaco0006@umn.edu>> wrote:
For "Fake MB Factor for SB" to show up in Special Tab, number of slices prescribed needs to be >1 and MultiBand factor = 1, along with the lines SBFakeSliceBands = 1 in MBAdvancedSettings.ini

________________________________

**Comment by mharms** [comment]
Can I ask why you want to do this?

**Comment by dilaraerisen** [comment]
@mharms in HCP Protocol Guidance recommends using SE-EPI sequences with opposite PE directions to estimate distortions in functional scans. It says this method is superior to traditional field map estimation methods for correcting distortions present in multiband fMRI data. To use spin-echo sequences in combination with MB sequences you need to do this, apparently. This is as far as I can answer your question. You can perhaps check the manual for further information.

@mix1007 thank you! This solved the missing "Fake MB factor for SB" tab issue. But now I'm having another problem. When I try to enter the value an error window pops up that says "An internal error occured. Your last change Fake MB factor for SB:1 -> 4 will be lost." Strangely, it allows 2 but gives this error for any other possible value. I am probably pushing my luck but do you have any idea why?

**Comment by mharms** [comment]
You don't need to use the SBFakeSliceBands feature for your SE-EPI acquisitions.  That is a feature that we indeed used back for the original HCP-YA acquisitions, but it isn't something we worry about any longer for the ongoing HCP-D/A (Lifespan) acquisitions (because we determined that including "fake" slice bands as part of the SE-EPI didn't matter in terms of the accuracy/quality of the distortion correction). You can find protocols available for import here: http://protocols.humanconnectome.org/

**Comment by dilaraerisen** [comment]
Thank you! And oops :)
