### ISSUE TITLE
Image noise as black dots on DTI images based on multi-band sequence (VD13D)

### ISSUE THREAD

**Issue by BeijingT** [CMRR-C2P/MB#119]
The reconstructed diffusion tensor images based on multi-band sequence for human brain always contain severe noise as black dots. All images of a series have black dots, which hinder the diagnosis.

The sample images and corresponding protocols are presented as follows:

![01](https://cloud.githubusercontent.com/assets/18691732/14840428/da9243fe-0c66-11e6-95bb-927fae884dff.jpg)
![mb 1](https://cloud.githubusercontent.com/assets/18691732/14840465/1aa46058-0c67-11e6-83cb-93efcb984b31.jpg)
[MB Q 4 Print_out.pdf](https://github.com/CMRR-C2P/MB/files/237853/MB.Q.4.Print_out.pdf)

**Comment by eauerbach** [comment]
I'm not sure exactly what is going on in this case, but I can speculate that this is one of the known problems with the online postprocessing routines, which is why I do not recommend using them. For example, we have enabled 16-bit DICOM images to improve dynamic range, but the Siemens postprocessing tools for the most part are not compatible with 16-bit images.

If you really want to use the online postprocessing tools then you must ensure that the pixel values do not exceed 4095 in any of the original (diffusion-weighted) images by adjusting the scale factors ("FFT scale factor" on the Sequence//Special card for VB-versions, "Img. Scale Cor." on the System//Tx/Rx card for VD/VE-versions). This can be tedious because absolute image intensity varies a lot depending on exact sequence parameters, coils, and samples. Of course this is exactly why we decided to go with the 16-bit option as the default.
