### ISSUE TITLE
Optical trigger problem

### ISSUE THREAD

**Issue by RAWaggoner** [CMRR-C2P/MB#123]
We recently experienced the problem that optical trigger signal stopped part the way through an fMRI run with version R013a of the MB-EPI sequence on a PRISMA running VD13D.  I can't say for certain that the pulse sequence is at fault, but we have only experienced this with the mutliband sequence. The subsequent runs in the same session were fine so it seems unlikely that this is a hardware problem.  Even in the problem run, the imaging was not affected.  The run otherwise finished normally and the images looked fine.  The trigger scheme was set to standard.

Is this a know issue? I have search the site but have not found any relevant posts.  

Any ideas?

Thanks,
Allen

**Comment by eauerbach** [comment]
There is really nothing special about the triggering in the MB sequence, so I can't think of any way the sequence is directly involved. Possibly you are using much shorter TR with the MB sequence, which is more demanding on whatever you are using to monitor the triggers. A 10 usec trigger is easy to miss. A long time ago I included a pulse stretcher in the optical-TTL converter device we provide on all of our systems; it stretches out the pulse to a few ms, and I haven't heard any complaints about this issue since.
