### ISSUE TITLE
R014: image reconstruction error on Prisma 3T VD13D

### ISSUE THREAD

**Issue by pmolfese** [CMRR-C2P/MB#130]
Been dealing with this since a software patch even on R013.  Whenever we try to begin a CMRR sequence (DTI or EPI), we get an error that says "Reconstruction Failed".  Odd since everything worked until the "Service Pack", and we're literally running sequences that we have collected data on previously.  

Save Logs: https://dl.dropboxusercontent.com/u/94909/UConn_cmrr_debug.zip

**Comment by eauerbach** [comment]
I can see in the logs that there is a problem activating the GPU; I guess when this service pack was installed it triggered a reinstall of the MaRS, but it looks like that install partially failed. In any case it is a problem on the Siemens end. Very few product sequences use the GPU, so maybe you don't notice anything unusual when using other sequences, but my reconstruction code will definitely fail if a GPU is present but doesn't work for some unexpected reason.

Running these commands (from the Windows host) should fix the problem by forcing the NVIDIA driver to reinstall:

`ssh root@mars "/opt/med/config/scripts/med.rc.boot/installNVIDIA.sh remove"`
`ssh root@mars reboot`

Otherwise, you could ask service to reinstall the OS on the MaRS, which should fix this and maybe some other things... Or you can do it yourself:

`reinstall_mars.bat`

I think that script will reboot the MaRS automatically and it will take something like 20 minutes longer than normal to come back up.
