### ISSUE TITLE
mbep2d_bold_VE11B_R014: slow reconstruction 

### ISSUE THREAD

**Issue by aamadon** [CMRR-C2P/MB#135]
Hi, there, it seems that ever since we moved from R013 to R014 on our Prisma (under VE11B), the bold sequence reconstruction takes much longer than before. The RF coil used is the 64-channel head coil, with HC1-7 receive elements on in both conditions below:

1/ R013: in a typical time series with TR=2s, MB=3, iPAT=2, there used to be a constant time delay of 7 images between acquisition and reconstruction.

2/ R014: now this delay is 27 repetitions after 5 minutes acquiring, and 43 repetitions after 11 minutes (end of sequence). 

Nevertheless, this delay seems to reduce if the head is replaced with a simple uniform phantom. Do you expect that the reconstruction time is dependent on the content of the images ?

Thank you for your feedback.

**Comment by eauerbach** [comment]
Are you using the Siemens channel compression option (Matrix Optimization = Performance)? That could explain the difference between head and phantom results, if the Siemens channel compression is calculated per study from the image data and it somehow works better for phantoms (I don't know the details of their implementation).

Otherwise, I'm surprised that from R013 to R014 it is slower. The main difference between the versions is the addition of GPU support, which should almost always be faster. Perhaps you have an unusually slow GPU. Can you show me the contents of this file:

`C:\MedCom\MCIR\Med\config\eja_hardware.ini`

**Comment by aamadon** [comment]
Hi,

Thank you for your feedback. I just checked on our Prisma, and the answer is no, we do not use the channel compression option.
Now here is the content of the eja_hardware.ini file :

[MARS]
NumberOfGPUs = 2
GPUComputeCapability = 3.0

# Mon Sep 26 07:31:51 2016
# +------------------------------------------------------+
# | NVIDIA-SMI 5.319.37   Driver Version: 319.37         |
# |-------------------------------+----------------------+----------------------+
# | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
# | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
# |===============================+======================+======================|
# |   0  Tesla K10.G1.8GB    Off  | 0000:8D:00.0     Off |                    0 |
# | N/A   34C    P0    43W / 117W |        9MB /  3583MB |      0%      Default |
# +-------------------------------+----------------------+----------------------+
# |   1  Tesla K10.G1.8GB    Off  | 0000:8E:00.0     Off |                    0 |
# | N/A   33C    P0    36W / 117W |        9MB /  3583MB |      0%      Default |
# +-------------------------------+----------------------+----------------------+
#
# +-----------------------------------------------------------------------------+
# | Compute processes:                                               GPU Memory |
# |  GPU       PID  Process name                                     Usage      |
# |=============================================================================|
# |  No running compute processes found                                         |
# +-----------------------------------------------------------------------------+

Best regards,

Alexis Amadon
CEA-Saclay
NeuroSpin / UNIRS
Bât. 145
91191 Gif-sur-Yvette Cedex
France
Tél : +33 1 69 08 79 05

De : Eddie Auerbach [mailto:notifications@github.com]
Envoyé : vendredi 23 septembre 2016 18:45
À : CMRR-C2P/MB
Cc : AMADON Alexis; Author
Objet : Re: [CMRR-C2P/MB] mbep2d_bold_VE11B_R014: slow reconstruction (#135)


Are you using the Siemens channel compression option (Matrix Optimization = Performance)? That could explain the difference between head and phantom results, if the Siemens channel compression is calculated per study from the image data and it somehow works better for phantoms (I don't know the details of their implementation).

Otherwise, I'm surprised that from R013 to R014 it is slower. The main difference between the versions is the addition of GPU support, which should almost always be faster. Perhaps you have an unusually slow GPU. Can you show me the contents of this file:

C:\MedCom\MCIR\Med\config\eja_hardware.ini

**Comment by eauerbach** [comment]
Unfortunately it appears Siemens has switched from dual Tesla C2075 GPUs to a single Tesla K10 GPU in their latest MaRS. They may think it is an upgrade, but especially for double precision calculations (which the slice-GRAPPA kernel fitting requires) it is a huge downgrade, like 80% slower. It also has less memory. We are currently trying to get the MaRS replaced in our latest Prisma because of this, but I will see if I can come up with some kind of solution for those who are stuck with a K10. I hate to disable the GPU entirely, but I'm not sure it is helpful.

**Comment by eauerbach** [comment]
Ok, upon further inspection on our new Prisma which has a K10 installed, I found that Siemens is not configuring it correctly. In their system-level configuration it is showing up as a single GPU, while it should really be addressed as two. My ICE program was unfortunately respecting the incorrect Siemens configuration and using only half of the available capacity (as is the product ICE...).

I have just posted a new version of the ICE for VE11A/B/C which fixes this issue. It should be considerably faster now (but K10 is still a lousy choice of GPU).

If anyone has a K10 on a VD13x system I haven't heard about it; I can update those versions upon request.

**Comment by aamadon** [comment]
Thank you much, Eddie.

**Comment by TimmWetzel** [comment]
Hello,

we will soon get a K10-based imager together with the VE11C upgrade for our 128-channel Prisma_fit. Are the performance issues completely fixed with the last version, or should we expect degraded performance compared to our current VD13D system (2x C2075)? We are mostly using the 64-channel head coil.

Regards,
Timm

**Comment by aamadon** [comment]
Hi Timm,

As far as I can tell (MB3, iPAT2, 1.5 mm isotropic resolution, full brain in TR=2s), yes, the performance issues have been completely solved with the last version. Thank you for the fix.

Best,

Alexis Amadon
CEA-Saclay
NeuroSpin / UNIRS
Bât. 145
91191 Gif-sur-Yvette Cedex
France
Tél : +33 1 69 08 79 05

De : TimmWetzel [mailto:notifications@github.com]
Envoyé : lundi 21 novembre 2016 14:25
À : CMRR-C2P/MB
Cc : AMADON Alexis; Author
Objet : Re: [CMRR-C2P/MB] mbep2d_bold_VE11B_R014: slow reconstruction (#135)


Hello,

we will soon get a K10-based imager together with the VE11C upgrade for our 128-channel Prisma_fit. Are the performance issues completely fixed with the last version, or should we expect degraded performance compared to our current VD13D system (2x C2075)? We are mostly using the 64-channel head coil.

Regards,
Timm

**Comment by eauerbach** [comment]
I'm really not sure. It should not be terribly worse (there was a bug; it has been fixed), but most likely there will be a longer delay before the first image appears. After that, it is possible that it could catch up quickly and eventually be faster over the course of a long scan.
