### ISSUE TITLE
RF power absorption limiter Error for CMRR_MB_EPI_VB17A_R014 

### ISSUE THREAD

**Issue by zongxp** [CMRR-C2P/MB#136]
Hi,

```
  We are getting a "RF power absorption limiter Error" with the latest mbep2d_bold sequence for VB17  on our 7T scanner.  The error occurs during the scan, after acquiring 140 or 150 images and is reproducible after scanner reboot.  Siemens engineer did tests and did not found any problem with the scanner.  Is there a way to avoid this error?  Changing the sequence parameters did not seem to help.
```

Thanks,

Xiaopeng Zong

![error_cmrr_mb](https://cloud.githubusercontent.com/assets/6616287/19818859/bd614614-9d1f-11e6-8351-5c2c8f46cc69.jpg)

**Comment by eauerbach** [comment]
This is pretty strange; typically on 7T the power limits are measured too conservatively. Did the Siemens engineer do the "RF Verify" QA? Otherwise, in case you are only seeing this when using an oil phantom (as in the image you show), perhaps it would better to use a loading phantom.

**Comment by h-you-man** [comment]
We had this problem too, while scanning a human, not phantom (VB17A, Verio). I'd say we faced it several times past month.
Is there any thoughts or maybe solutions about?

**Comment by RJB0018** [comment]
We're past and presently having the same problem here at Auburn University on our Siemens 7T.  Past releases and most current release (R016a) throw us “RF Power Limiter" error issues that stop our scans.  This error occurs only with the CMRR sequence and we’ve been having the problem for about 2 years running.  The RF error pops up and stops the scan 4 to 5 minutes after the scan has been running. Before the scans start, normal/acceptable SAR values are indicated.  Repeat run attempts result with the same error unless we manually lower the TXref level to sub-optimal lower values.

Has anybody found a fix yet?  Anybody from CMRR wish to reply?

Our 7T scanner configuration includes: software VB17A-UHF, RF Step-One transmit hardware, and NOVA head coil (32-chan Rx, 1-chan Tx).  We approached Siemens with the problem and they deflected blame back to the sequence design.

**Comment by eauerbach** [comment]
My initial response was not very helpful -- these are likely all examples of the known power overestimation error of the 7T online power monitoring hardware. For RF pulses that are highly amplitude modulated, as multi-band pulses typically are, the slow response of the power monitor tends to measure an envelope of the RF pulse rather than the true shape. However, the true shape is still used for the SAR prediction calculated by the sequence (SAR % in the lower right corner of the screen). So although you might see a predicted SAR of as low as 60-70% for a given protocol (which is accurate), the online monitor will often measure something much higher and stop the scan.

There is no proper solution available (the power monitoring hardware needs to be upgraded, which it has been somewhat on the Tim4G and Step2 platforms), but there are some partial workarounds. The easiest is to enable the "phase scrambling" option, which reduces the amplitude modulation (and the peak) of the RF pulse. Another option is the time-shifted RF option (only for spin-echo sequences), or a combination of both options.

We had an abstract on this issue years ago: Proc. ISMRM 22 (2014) #1377.
