### ISSUE TITLE
Add option to save non-PSN data for mbep2d_diff (R014, VB17A)

### ISSUE THREAD

**Issue by BenInglis** [CMRR-C2P/MB#144]
A few of us are investigating whether Prescan Normalization, or similar, may be useful (even essential) to get good data with monopolar DW when using the 64-ch head coil on a Prisma. The working hypothesis is that the eddy current-induced distortions & shifts act a lot like motion and impose Rx-field contrast across the images in ways that tend to anchor standard realignment algorithms that are used in post-processing. I would like to test on my Trio with 32-ch coil for similar phenomena and would like to have an easy way to add both raw & PSN data to the patient database without having to Retro Recon in the session. Any chance you could enable the option to save non-normalized images with PSN, as already exists for the mbep2d_bold sequence? Thanks!

**Comment by eauerbach** [comment]
The reason the unfiltered option is disabled in the product is because it is not supported by the various post-processing options (presumably causes them to crash). Actually, as of VD13/VE11, it is disabled for BOLD as well. If I re-enable the option, I have to balance the utility of the option against the number of complaints I will get from users about their reconstruction crashing.

Since your interest is speculative at this point and you are the only one asking about it, and since the option of retro recon exists and you know how to do it, I'm inclined to not make a change at this point. If you think this is something that would be essential for routine studies in the future, however, then perhaps I could make it available as an "advanced" option in a future release.

**Comment by BenInglis** [comment]
Hi Eddie, that's fine. Another option is for people to keep Prescan Norm off but to acquire a separate Rx bias field and apply it offline.
