### ISSUE TITLE
R014 version of multiband sequence for BOLD on VE11C Prisma will stop in the middle

### ISSUE THREAD

**Issue by lli36** [CMRR-C2P/MB#149]
Hi, 

We recently found that R014 version of the multiband sequence for BOLD will hault in the middle of scan on VE11C Prisma. The multiband factor is 8 and 64-channel head/neck coil is used. The problem stopped when we turned on "matrix optimization" option in the system/miscellaneous. Could someone provide a link on more detailed information about the matrix optimization? Although turning on the option will get rid of the problem, we want to know more about the method, to avoid any potential issues in data reconstruction. 

Thank you!
Longchuan

**Comment by eauerbach** [comment]
"Matrix optimization" is the product Siemens channel compression option. I don't have any specific details about the algorithm, but possibly Siemens has a reference. The reason for the crash is probably insufficient memory on the GPUs for the large matrix sizes when using the 64-channel coil. Since relatively few people use the 64-channel coil, and since matrix optimization seems to address the problem with little or no consequence, it hasn't been a high priority to investigate much further.
