### ISSUE TITLE
Release R015 for VE11B won't install

### ISSUE THREAD

**Issue by PBKingsley** [CMRR-C2P/MB#155]
I tried to install Multi-Band EPI Release R015 for VE11B on our Siemens 3T Prisma.  It went through several steps, then said "Done!" but it lost connection to the MARS computer, and now all connection to the MARS computer is lost and we cannot use the scanner.  Has anyone else had this problem?  Any work-arounds?

**Comment by swrieger** [comment]
It sounds like for some reason MARS isn't restarting. You could try to
reboot it manually if you know where it is, or simply shut down the scanner
completely and power it up again. With any luck that should fix it.

Cheers,

Seb


On 15 Mar 2017 12:25 am, "PBKingsley" <notifications@github.com> wrote:

I tried to install Multi-Band EPI Release R015 for VE11B on our Siemens 3T
Prisma. It went through several steps, then said "Done!" but it lost
connection to the MARS computer, and now all connection to the MARS
computer is lost and we cannot use the scanner. Has anyone else had this
problem? Any work-arounds?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CMRR-C2P/MB/issues/155>, or mute the thread

**Comment by PBKingsley** [comment]
The engineer was able to connect to MARS through an alternative entry, but not via the normal routes (ethernet?), so it seems that MARS restarted but could not communicate.  After several reboots failed to solve the problem, he decided to back up our protocols and re-install the original software.  So we can't put the current multi-band release on our scanner until this problem is fixed.

Peter Kingsley
________________________________________

**Comment by eauerbach** [comment]
Without a savelog it is impossible to know for sure what happened on your system, but there is certainly no fundamental problem with the current release for VE11B as it is successfully in use on many systems including one of our own. Very little changed since R014, and nothing that could explain this.

The installer does perform a full reboot of the MaRS, which could coincidentally expose unrelated problems. Ordinarily the MaRS is only fully rebooted if the complete system is power cycled. So anything that happened since the last power cycle could appear to have been caused by installing the MB sequences...

I just can't think of any way installing the MB sequence package could cause the MaRS to become inaccessible via SSH. One site had a very strange problem where the GPU detection boot script included in the MB package became encrypted (involving a specific chain of events extracting the zip file to a USB disk using a Mac), and this caused the boot process to fail before the Siemens processes could be started. The installer has been updated to check for this rare situation, however, and in any case this would not affect SSH (which is started much earlier in the boot process).

**Comment by argyelan** [comment]
I am working with Peter Kingsley, and we are one of the imaging groups that is affected by this issue. Maybe this is a naive question: but is there a way to get a new license file only, since the old installation worked just fine, so maybe we just change the license file and able to keep going on.   

Also, somewhat unrelated, but curious: how can we figure out in advance if a license file is going to expire? (we did not get any warning, and it did happen in middle of a relatively important scan)
