### ISSUE TITLE
[R015 E11C]Offline reconstruction

### ISSUE THREAD

**Issue by leizhouEmory** [CMRR-C2P/MB#157]
We are using your R015 version of Multiband sequence on our Siemens 3T Prisma MR scanner.  One of our PI used to save Single-band reference images when doing multiband scans for normalization purpose.  However, due to a SMS-EPI license glitch, our R014-R015 update got the "Save Single-band reference in separate series" switch unchecked and the single band images was not saved.  I have saved the RAID files for the corresponding scans.  I am wondering if there is a way to offline reconstruct the single-band reference images out of the k-space RAID file?  Any help will be very appreciated.
Thank you very much!

**Comment by dkbjornn** [comment]
Is there any update on this? We've been having issues with our remote reconstruction and it will stop the EPI sequence mid-run. We've narrowed it down to an issue with the imager running out of memory. Rather than having to wait a few minutes in between each run for the previous sequence to reconstruct, we thought about just doing the reconstruction offline. It's there a way we could reconstruct post-scan from k-space?

**Comment by vkemper** [comment]
Just guessing here:
@leizhouEmory It should be possible to retro-reconstruct the single band images from the dat files after importing them back onto the RAID. You have to find the corresponding switch that represents the boolean on the special card. The easiest way is probably to run two test measurements with and without single band reference images and compare the protocols. Some parameters in the wipmemblock will be different and it might be enough to change them in the data that you want to have reconstructed with single band reference images.
@dkbjornn Certainly not the best solution, but what you could do is use the ideacmdtool to use the EmptyIceProgram that wont do anything during the scan. When the scanner is otherwise unused you can retro-reconstruct the data from the raid in TWIX. Make sure it doesnt get overwritten in the meantime because the RAID can quite limited in size. The obvious downsides of this approach are the extra machine time only for reconstruction and the fact that you wont be able to inspect your images while scanning. The better solution would be to get a more powerful imager if possible.

**Comment by eauerbach** [comment]
To turn on SB reference export in a retro recon (initiated from Twix), you will need to edit the XProtocol and add 1 to the value of `YAPS.alICEProgramPara.18` before starting the reconstruction.

To acquire with no online reconstruction and reconstruct later offline, you can choose "Online multi-band recon." = "None" in the UI when scanning. Then when you initiate the retro recon in Twix you will need to change the parameter `YAPS.alICEProgramPara.16` from 1 to 3. You will also need to manually set the slice-GRAPPA kernel size by entering a value in `YAPS.alICEProgramPara.17`. By default this would be 3 (3x3) for MB2 and MB3, or 5 (5x5) for higher MB factors.
