### ISSUE TITLE
No images reconstructed for diffusion sequence (Prisma 3T VD13D)

### ISSUE THREAD

**Issue by claus-magdeburg** [CMRR-C2P/MB#162]
A DTI protocol tends to crash in a certain way. That has started yesterday. Before yesterday we had no problems at all with the protocol, but now it happened twice for three attempts. So, the problem is not reproducible, but when it happens the sequence runs and finishes without giving any error messages or other indications of a problem. However, no images are reconstructed. After that the system seems to be in a shaky status. Not even a localizer can be reconstructed (but it can be started and it runs without error messages). Restarting MARS does not help, but it yields a lot of strange error messages probably unrelated to the root cause (e.g. E-shim overheating). In such a situation the system reports connection problems between host computer and MARS, but I assume that that is just an effect of the very busy MARS (doing whatever).

Shutting down the system completely and restarting it helps.

Has anybody seen a similar behavior? Any recommendations? I can send savelog-files if somebody tells me where to put them. They are too big for an attachment here or with an email.

If you need more details regarding the parameters, I can provide them.

We did not have that problem with any product sequence, so Siemens tells us that they cannot really help us.

Thanks in advance for any suggestions

Claus

**Comment by eauerbach** [comment]
We had this problem on VD13D and a couple other sites had it as well. In our case we could reproduce it with the product sequence, but it took a concerted effort because people do not normally run the product sequence with such demanding protocols. Siemens replaced the MaRS and host computers a few times to no avail. Whatever the problem is (Siemens never officially acknowledged it), it seems to be specific to VD13D and is "cured" by upgrading to VE11B or VE11C.
