### ISSUE TITLE
R016 printing protocols

### ISSUE THREAD

**Issue by dgwakeman** [CMRR-C2P/MB#186]
Hi All,

I was trying to print my phase 1B protocol, and none of the CMRR sequences are printing to the protocol. Were any strange compile flags tweaked in the latest release? (they show up in the table of contents, but the individual sequence parameters don't show up). Sorry, details this is on a VE11C Prisma Fit 

Thanks!
Dan

**Comment by sshannon67** [comment]
Hello, 
We are experiencing this same feature on the same platform.  All non CMRR protocols are created but not the CMRR ones.  The scans run, we just can not print protocols to PDF.

**Comment by eauerbach** [comment]
I have identified the problem. It will be fixed in R016a.

In the meantime, however, you can correct it manually by opening the **Sequence/Part 2** card of the affected protocol(s) and setting the **Excitation** mode to **Standard**. For the protocols that will not print, you will find this field is blank.

This issue only applies to protocols created with sequences prior to R016, only for software versions VE11A/B/C, and only for systems with pTX capability (Prisma, some Skyras). Very fun to troubleshoot.

**Comment by dgwakeman** [comment]
Thank You!

**Comment by dgwakeman** [comment]
@eauerbach this won't change the sequence at all will it? Does the "null" state default to "Standard" mode?

**Comment by eauerbach** [comment]
Correct. In the future there may be other options in that field for different types of pTX pulses, but right now the value is not checked or used at all by the sequence.

**Comment by eauerbach** [comment]
R016a is released and fixes this issue.
