### ISSUE TITLE
HCP Multi-band 2 Sequence Compatibility after Skyra upgrade to version VE11C

### ISSUE THREAD

**Issue by eboorman** [CMRR-C2P/MB#192]
Hello, 

I am writing to inquire about the likely compatibility of data obtained using a CMMR sequence we currently have implemented at UC Davis, where I am a PI, pre- and post-upgrade. The Skyra scanner here is going to be "upgraded", what Siemens apparently call "Evolve" to a new software version VE11C. The sequence we use is the HCP multi band 2, no GRAPPA. Happy to provide further details. What I would like to know is whether the data acquired before this "Evolution" can be easily combined with data acquired afterwards in the same study. The physicists here at UCD seem to be unsure. 

Any advice would be greatly appreciated. 

Yours sincerely,
-Erie Boorman

**Comment by eauerbach** [comment]
There are no significant differences in the sequence and reconstruction code on our side, but there is really no comprehensive documentation of the changes Siemens may have made on the system level and how much that might affect your data. You could notice that the images systematically have more or less SNR or more or fewer artifacts after the upgrade, but it is hard to say whether that would be detectable.

I would say there isn't much of a difference; I personally haven't noticed any remarkable differences in image quality between VD13D/VE11B/VE11C on our Prismas, and there aren't any miracles implemented in VE11C I am aware of. It really depends on exactly the type of data you are collecting and how you are analyzing it.

One significant issue could be that with VE11C you must purchase the SMS license from Siemens in order to continue using our sequences. This is a new requirement imposed by Siemens as of VE11C. You will want to work this out prior to the upgrade if possible to avoid downtime.
