### ISSUE TITLE
Problem with recording external triggers

### ISSUE THREAD

**Issue by huchengMRI** [CMRR-C2P/MB#196]
Hi Eddie,

We are on VE11B. The CMRR_MB_BOLD sequence can record pulse and resp signals but not the external trigger generated by the sequence itself (we used the trigger signal generated by the sequence as external input). However, the external signal can be saved through ideacmdtool. We measured the TTL external signal, the amplitude is around 5 volts and the duration is 10 ms.  
Thanks,

Hu

**Comment by julfou81** [comment]
Hi,

We are on prisma VE11B and we are able to record the external trigger. Looking at the file XX_EXT.log (created along side with XXX_Info.log when the option "file" is selected for "Physio. Recording" in the special tab), I noticed that the sample time is 8 tics, i.e. 20 ms. At first we were not able to record the external pulse either. Only the file XXX.log was created. It is due to the fact that the duration of the external trigger was too short (10 ms, like you). We switched to a duration of 250ms and the file XXX_EXT.log was saved and all the "EXT1_TRIGGER" were detected.  However this recording is not very precise due to this 20 ms sampling time. The option "legacy" gives another format of file (XXX.ext), not as easy to use but where the sampling information is recorded every 2.5ms.
