### ISSUE TITLE
32 vs 64 channel headcoil, pre-scan normalize, Prisma

### ISSUE THREAD

**Issue by fissell** [CMRR-C2P/MB#198]
Hi,
We are running multiband 3 for diffusion imaging on a Prisma VE11C scanner.
CMRR release 016a.
Is there a recommendation for using the 32 versus the 64 channel headcoil ?
For each of those headcoils, is there a recommendation re using the prescan normalize option ?
(btw, having that option to save raw data with and w/o PSN would be helpful).

thanks,
Kate

**Comment by eauerbach** [comment]
For MB3 I wouldn't expect a significant difference between the 32-channel and 64-channel head coils. At higher acceleration factors (MB+iPAT) the 32-channel coil tends to be preferred. If you use the 64-channel coil, be sure to select the matrix optimization option to keep the reconstruction time reasonable.

For diffusion we recommend using the SENSE1 coil combination option. I don't think it helps to also use prescan normalize in that case?

**Comment by BenInglis** [comment]
Hi Eddie, I think the main concern is the effect of eddy current correction on DWI that have strong Rx bias fields. The benefits may not become apparent until much offline processing. It only just hit me that a workaround to not having raw and Prescan Normalized data is to acquire the DWI with Prescan Norm off, but to acquire a separate Rx bias field map. (Might as well get a Tx field map while we're at it, since these take tens of seconds.) 
Kate, I'll email you separately about setting up the Rx (and Tx) bias field acquisition.

**Comment by fissell** [comment]
Thanks Eddie and Ben.
Ben, if you could post or email the protocol for acquiring Rx and Tx field maps that would be much appreciated.

Eddie:  We are using the SENSE1 coil combine.  Does that use a coil weighting scheme that makes
PSN unhelpful ?   Would it make PSN actually detrimental ?  And, just to be clear, are you saying the SENSE1 coil combine algorithm is the same for the 32 and 64 channel headcoils ?
