### ISSUE TITLE
Recurring reconstruction failure with VB19A

### ISSUE THREAD

**Issue by greggfer** [CMRR-C2P/MB#200]
Multiband use among our clients has surpassed standard BOLD collection at our center in recent months.
Over the last month, every 6 days, the scanner stops running with the following message: Image reconstruction failed MeasUid  210. Attempts to restart a sequence with the same study fail.
Rebooting the Trio or starting a new study is successful. 
We are using a remote reconstructor connected to the Trio's MRIR for multiband reconstruction. The error log on the reconstruction PC have no events listed. 
Has anyone here had a similar issue? If so, any thoughts on how to resolve it?

**Comment by eauerbach** [comment]
Do you still have an old Step4 MRIR? Some of those only had 16 GB of RAM and this was unfortunately a known limitation. The only "solution" was to restart the MRIR regularly (or at least the MrIrisContainer process) to make sure every bit of memory was free and unfragmented, since there was little room for error. Lately it seemed most of those old Step4 either died and were replaced with the 32 GB version, or were upgraded to Step5, so this fell off as an open issue...

Another possibility: the next version of the ICE program that I am currently working on has a change which should result in it using a little bit less memory. This could be enough to solve your problems, but I don't know for sure--perhaps it will make no difference. I could offer you the new version to try if you like.

**Comment by greggfer** [comment]
I learned from Siemens that we currently have the Step 5 MRIR with 32 IRX. They could not tell me if it is 16 or 32GB.

We are interested in the new version of ICE. If you'd be willing to send it to us we'll try it out. 
Thank you for your help!
