### ISSUE TITLE
No cmrr_mbep2d_* Showed up under Exam Explorer after Installation

### ISSUE THREAD

**Issue by EthanAaronShelton** [CMRR-C2P/MB#201]
Downloaded two versions as below for our MAGNETOM 7T 1-ch mode:

1) Release R016a for VB17A (build 19-Dec-2017)
2) Release R016a for VB17A-UHF (UHF systems w/ GPU) (build 19-Dec-2017)

We have been using the 1st version (Release R016a for VB17A) for over 1 year, and everything went smooth. Recently I tried to install the 2nd version (Release R016a for VB17A-UHF, although our system doesn't have any GPU for recon), and the installer program went successfully as shown in the cmd.exe window. Then I tried to insert sequences in Exam Explorer, but couldn't find any cmrr_mbep2d_* under USER. I tried to reboot the scanner and application, but same problem persisted. So I had to re-install the 1st version and everything went back to normal. 

Anything I may do wrong? Your comments/advice is appreciated.
-Shelton

**Comment by eauerbach** [comment]
If you don't have a GPU in the imager, then the standard VB17A version is the correct one to use. The VB17A-UHF version should also work (with no advantage if you don't have a GPU), but it turns out the copy of R016a for VB17A-UHF that was on the web page before today was broken. This is now fixed. If you do eventually get the "Titanium 20" imager upgrade (which has a K8 GPU) then you should download and install a new copy of the (fixed) VB17A-UHF version which has GPU support.
