### ISSUE TITLE
Problem with the B values in diff Sequence

### ISSUE THREAD

**Issue by tragus1** [CMRR-C2P/MB#205]
I'm using the CMRR mbep2d_diff sequence with MB factor of 3. I set the B-Values to 0 and 2000 bipolar mode but I'm receiving the following bvals:
0 200 200 200 500 500 500 500 505 500 1000 0 995 1000 1000 1000 1000 1000 1000 1005 1000 1000 0 1000 1000 1005 1000 1000 995 995 1005 1000 995 0 1005 1000 1000 1000 1000 995 1000 1000 995 2000 0 2005 2000 1995 2000 2000 2005 2000 2005 2000 2000 0 2000 1995 2000 1995 1995 2000 2000 2005 2000 2000 0 2005 2000 2005 2005 2005 1995 1995 2000 1995 2000 0 2000 1995 1995 1995 2005 1995 2000 2000 2005 2000 0 2005 1995 2005 1995 2005 2005 2000 1995 2000 2005 0 2000 2000 2000 2000 2000 2005 1995 2000 2000

How can I built a sequence acquiring only 0 and 2000? Does anyone has an idea what's wrong with the sequence parameters?

Thank you,
Tragus

**Comment by BenInglis** [comment]
Hi Tragus, please see closed issue #188 for advice. You'll need to ensure that the b values in the DIffusionVectors.txt file (or equivalent on later s/w) are appropriate and, if necessary, normalized. (Some protocols, such as that used by UK Biobank, intentionally use half and full b values interleaved, to get two diffusion shells.) If you run MDDW mode instead of FREE, you will force normalization. Then, you should see consistent b values throughout. If you wish to return to using FREE mode, you'll need to either create a new set of diffusion vectors, or change the normalization.
