### ISSUE TITLE
MB-ME Epi BOLD Prisma Fit V13D - artefact

### ISSUE THREAD

**Issue by mzvyagintsev** [CMRR-C2P/MB#207]
Hello

I am using the MB epi BOLD sequence with Factor 3 and Multi-echo - 4 echos, whole brain. I started to notice artifacts in some volumes (present in all 4 echos). Any idea what the problem it can be? Any recommendation?
The picture of the artifact is provided.

Thanks,
Michael

![image001](https://user-images.githubusercontent.com/38751371/39296161-76fe81d6-4940-11e8-9784-0bd39a77927e.png)
![007_1324](https://user-images.githubusercontent.com/38751371/39296800-21205ec2-4942-11e8-94c3-87e04be243a0.png)

**Comment by BenInglis** [comment]
That's RF interference. Given the generally preserved shape of the brain in the contaminated slices, I'd say it's most likely some sort of conductive debris lodged in an RF coil connector socket rather than in the gradients. Check out examples at: https://practicalfmri.blogspot.com/2012/05/rare-intermittent-epi-artifacts-spiking.html  See source 3 in particular.

If you haven't already, try reproducing on a phantom. If you can't, most likely the debris has been removed with a coil swap. Otherwise, if the problem persists, check the sockets for debris, especially tiny ferrous metal particles that can easily track into the magnet room and get sucked up into the magnet bore. (As a standard procedure for our weekly cleaning, we use masking tape to remove metallic particles around the magnet bore.) Also check the general condition of metal connectors on the bed sockets and on the coil plugs. The Prisma coil connectors are flat, not pins like on the Trio, if memory serves. So they should be less susceptible to damage. Still, check the plug condition before each use, and also check the sockets for debris as standard procedure.

Cheers!
