### ISSUE TITLE
Trio shim tray Breakage during multiband using MB acceleration of 8

### ISSUE THREAD

**Issue by greggfer** [CMRR-C2P/MB#208]
We have a researcher running the mutiband sequence on the Trio (VB19A) an using a MB factor of 8 and a TR of 785ms. The user runs 10-12 - 7 minute scans using this setup. On two occasions this week, each time on the 9th run, one of the scanner's shim trays broke and the shim plate moved enough to warrant major repair work.
We are trying to troubleshoot the root cause of this issue. We suspect the high MB acceleration is a factot, if not the sole reason this keeps happening.
Has anyone else experienced a similar issue? And what do maximum MB factor do you recommend?
Thanks,
Gregg

**Comment by BenInglis** [comment]
Hi Gregg, the multiband factor is all RF, surely the shim tray problem is due to gradient vibration. Seems like a fairly typical wear & tear issue to me. (I am aware of at least one Trio, now upgraded with Prisma-fit, that had a shim tray break & move, and this happened before MB was around for the masses. As a result, I added recording of all shim values to my QA recording, so we could track if anything might be moving very slowly, with no apparent performance degradation at first. And this was over 5 yrs ago.)

Sounds to me like a heating effect, or the cumulative effects of vibration over time. It should be possible to get a similar effect with a product sequence set up to use very similar gradient magnitudes and timing. In-plane is trivial. For the slice dir, I would simply maintain the TR at 785 ms and reduce the number of slices to fit, to keep the gradient duty cycle approx equivalent to the MB scan. (The SMS pulses may require very slightly different slice select gradient strengths, but this is going to be a relatively small difference if the slice thickness is set the same.) Next, I'd run the same total duration, same number of runs. My wager: product EPI can trigger a similar failure at a similar point.

As to max MB factor, that very much depends on your RF coil - I don't advocate factors greater than 5 for axial slices on a 32ch coil - and on your use of LeakBlock. But this is a quite separate discussion than vibration and shim trays. 

Cheers!

**Comment by swrieger** [comment]
I've had shim trays fail on a Trio in the past as well. Old age, heat, and
vibration don't seem to get on well with the material used. Siemens
replaced them with a more recent version using glass fibre reinforced
plastic instead of the original plain plastic ones. Not had any problems
since, and all that machine does is multiband EPI all day long.

Cheers
Seb

**Comment by greggfer** [comment]
All useful information. Thanks, Beninglis and Seb. This makes sense as we ran 130+ subjects with this exact protocol without incident 2 years ago.
However, the same shim tray broke during this study on Monday, then again last night with a brand new one. So, unless there was a flaw in the new tray it is still a puzzle as to what keeps causing this. Since we only have one user who uses a MB factor of 8, we've been investigating this as the possible culpriit.

Cheers,
Gregg

**Comment by BenInglis** [comment]
You most likely have a mechanical resonance in the shim tray that this particular protocol just happens to aggravate. It happens. I had a particular user protocol that used to trigger arcing in old style gradient connectors, when no other protocols (including an old QA routine) would trigger them. Even the slice angle can be a deciding factor. 

One thing to keep in mind when using MB, or any advanced research scan come to that. Often there are concomitant changes that can precipitate unexpected issues. In the case of MB, the ability to cover full brain with 2 mm slices tempts us to increase the in-plane resolution to 2x2 mm, as well. This drives the in-plane gradients far, far harder than for more typical 3x3x3 mm voxels using plain EPI. This isn't the fault of MB - the in-plane performance is the same for MB as regular EPI - but the way we have decided to use the new feature. It's very easy to blame the headline feature and miss the incidental factors. (If you want another example of an unintended consequence of using MB, check out: https://practicalfmri.blogspot.com/2016/10/respiratory-oscillations-in-epi-and-sms.html.)

**Comment by greggfer** [comment]
Update: An inspection of the shim tray that broke showed that the lip of the tray where it screwed into the gradient coil melted, weakened and broke due to high heat in that one location. This high heat is apparently only occurring at this one point on the gradient coil. All the other shim trays look fine. This occurred twice in one week. Siemens is currently investigating the source of the heat and the reason it is localized. l'll post another update when we get an answer.

**Comment by BenInglis** [comment]
Definitely have Siemens assess the security of the screws or nuts & bolts. Moving metal can cause very high voltage arcs that will melt almost anything, including the metal itself if you give it enough use. We darn near burned our facility down many years ago, with arcing in the gradient filters in the wall behind the magnet. Some photos in this post:

https://practicalfmri.blogspot.com/2012/03/amazing-accounts-of-fires-in-and-around.html
