### ISSUE TITLE
MB-diffusion, unable to select multiple averages per b-value

### ISSUE THREAD

**Issue by wjoy111** [CMRR-C2P/MB#216]
I would like to run a diffusion scan with the following B-values/Averages

b-value = 0 / 1 average normal, 1 average with reversed PE/RO
b-value = 1000 / 2 averages.

Is this possible at all?  The averages field is greyed out, and seems to be hard coded at a value of 1.

Thanks,
Joy

**Comment by wjoy111** [comment]
Sorry, I wanted to add that I'm running version VE11C on a PrismaFit.

**Comment by eauerbach** [comment]
Averages are indeed disabled; the MB reconstruction is sensitive to intra-scan motion, so we really don't want to acquire data over multiple shots... It is currently not possible to acquire data with multiple PE/RO orientations within a single scan.

If you want multiple averages, the supported solution is to acquire multiple measurements and average them in postprocessing. This should always be preferred since you have the option of applying motion correction, etc. between the averages, which is not possible if the scanner combines them early in the reconstruction.

For the case you describe above, two scans, one "normal" and one with reversed PE/RO would seem to accomplish everything that you want.

**Comment by wjoy111** [comment]
Hi Eddie,

Thanks so much for your response.  We have set up multiple acquisitions as you have suggested.

Best,
Joy

Joy Williams, B.Sc.(Hons), MRT(MR)
MRI Technologist
York University, York MRI Facility
1010 Sherman Health Science Research Centre
4700 Keele Street
Toronto, ON M3J 1P3
416 736 2100 ext 44531
www.yorku.ca/mri
