### ISSUE TITLE
Running MB with acceleration factor of '1' as a "standard" EPI sequence

### ISSUE THREAD

**Issue by andregouws** [CMRR-C2P/MB#218]
Hi - this may seem like a silly question: Is there any reason why we shouldn't use the CMMR MB sequence as a "standard" EPI acquisition (i.e. no additional acceleration and with GRAPPA=2)?
I have run some test and appear to produce comparable output with stock Siemens ep2d and the MB sequence with those settings when I turn all the dials to the same values. Also, the dicom headers and protocol sheets confirm the similarities.. Is there any reason for me not to do this?

Any advice greatly received. Thanks

Andre'

(For the record, the main reason is because of the very useful option in the CMMR to collect physiological data without having to control the PMU offline).

**Comment by BenInglis** [comment]
Hi Andre, I had the same thought and discussed this with Essa a year or so ago. Specifically, I wanted to know if I could essentially discontinue local support of a sequence we call ep2d_neuro, based on ep2d_bold, that has some features like variable dummy scans, early/late partial Fourier option, etc. Almost all the functionality of ep2d_neuro now resides in CMRR sequences. Going forward, then, I plan to use CMRR sequences as our default research EPI sequences, whether or not we will be using MB. I have tested MB=1 without iPAT and, like you, found almost identical performance to ep2d_bold. 

Related: I had as a deliverable to Siemens some help docs for ep2d_neuro. They have agreed to accept help docs for CMRR sequences instead. These will be based on my blog posts. So I also plan to encourage all research sites to adopt CMRR sequences as their default for research apps, so that we can have wider usage, more testing & validation under a broader range of circumstances, and, hopefully, better parameter selection based on deeper understanding. Just the existence of help docs should be sufficient justification for many sites to adopt CMRR seqs over something else.

And of course, the more of us who rely on the sequences, and share the burden of testing, documentation, feedback, etc., the more likely it is that CMRR can get the resources needed to produce the code in the first place.

**Comment by andregouws** [comment]
Brilliant Ben. Thanks a bunch for the feedback (prompt)! 
A
