### ISSUE TITLE
BOLD value range in fMRI sequence

### ISSUE THREAD

**Issue by alexsayal** [CMRR-C2P/MB#221]
Hello,

During testing of a MB-EPI sequence, we encountered functional values in the order of the 20000, and not in the 500-1000 typical BOLD value range.

Is this to be expected? We noted that if BOLD->Motion Correction is turned on, this does not happen.

Thank you in advance,

**Comment by alexsayal** [comment]
These are the sequence parameters we are using, in a Siemens Prisma fit with a 64-channel head coil. 
[cmrr_SMS3.pdf](https://github.com/CMRR-C2P/MB/files/2676049/cmrr_SMS3.pdf)

**Comment by mharms** [comment]
Completely normal.  The sequences save DICOMs with full 16 bit dynamic range, rather than the typical 12 bits.  You just need to make sure that you aren't saturating the 16 bit range (i.e., values maxed out at 32767) and that your DICOM to NIFTI conversion can handle 16 bit DICOMs (which 'dcmniix' has been able to do for quite some time now).
