### ISSUE TITLE
offline intensity normalization

### ISSUE THREAD

**Issue by marinkakoenis** [CMRR-C2P/MB#232]
Hey All, 

Is there a way to do image intensity normalization (as done during acquisition) post-scan? For some scans in my study the normalized images were not saved.

R016a, BOLD-EPI, MB8, Siemens Skyra

Thanks. 

Marinka

**Comment by BenInglis** [comment]
Hi Marinka, if you have anatomical scans such as MP-RAGE for which you have both the raw and normalized images, you could construct a receive bias field from these and apply it to the MB-EPI data. It's also becoming increasingly common to acquire separate body receive and head coil receive images for post hoc Rx field normalization. The pair take about a minute. Then just do Rx bias field correction offline.

**Comment by marinkakoenis** [comment]
Hey Ben, Unfortunately none of the normalized scans were saved. (Old study when we were trying to save space, we saw our mistake soon enough and have adjusted parameters since then.)

**Comment by RAWaggoner** [comment]
Marinka,

There are a lot of tools available for doing intensity normalization.  Pretty much every tool for doing segmentation will generate a bias field.  You just need to run an EPI volume through the routine instead of an MP-RAGE image and then use the bias field map to normalize the intensity of each EPI volume.  FSL, SPM, and AFNI can all do this, as well as many other packages.  Doing this in FSL is very straight forward, in a terminal window just do these three commands

   Extract the first volume
>fslroi epi.nii epi_01.nii 0 1 

  Run FAST, the -b flag will save the bias field map
>fast -b epi_01.nii

 Divide each volume by the bias field map 
>fslmaths epi.nii -div epi_01_bias.nii epi_nm.nii

You can do something similar with 3dseg in AFNI, but the defaults in 3dseg are not well suited to EPI images, so you will need to play around with the flags to get a reasonable bias field map.

The segmentation utility in SPM works well, but the bias field maps it generates are inverted compared to FSL and AFNI.  So you need to multiply your epi volumes by the bias field map, rather than divide.

Good Luck,
Allen

**Comment by marinkakoenis** [comment]
Thanks Allen! I thought it would be more complex.
