### ISSUE TITLE
physioLog.SliceMap values

### ISSUE THREAD

**Issue by JJCbr** [CMRR-C2P/MB#234]
Hi All,

Thanks a lot for providing the very useful readCMMRPhysio() function.  I have a question regarding the values in row 1 and row 2 of the output field .SliceMap. In the script comments these are given as 'the start time stamp of each volume/slice' but I find row 2 is 20 timepoints behind row 1; what is the difference between these rows?

I also have a slight error in matching the timepoints between the output of readCMMRPhysio() and my scan parameters.  I have 214 TRs and taking the range of timepoints given in SliceMap values scaled to my TR I get 213.964 . Obviously this is a good approximation but I was wondering if I may have made a mistake as these do not match excatly (exact numbers given below).

Many Thanks,
Joe

TR = 2060 ms;
total physiological data timepoints collected: 191975
first SliceMap = 15638
last SliceMap = 191945
timepoints per TR = 2060/2.5 = 824
(191965-15638)/824 = 213.964

**Comment by eauerbach** [comment]
Sorry, the comment for (2,:,:) in the SliceMap should read "the finish time stamp". SliceMap(2,:)-SliceMap(1,:) will give you the actual EPI readout duration for each slice/volume. I expect it will jump around +/- 1 due to jitter in relation to the 2.5 ms clock.

If you are just comparing the first and last SliceMap values, you will not get the exact TR, since you will be comparing the start of the first readout of the first slice with the end of the last readout of the last slice. You will be off by something like TR/nSlices less one readout duration.

For a better sanity check I guess you could look at (SliceMap(1,:,end)-SliceMap(1,:,1))/824; that should give you something very close to 213 (nMeasurements-1).

**Comment by JZcam** [comment]
Hi Eddie,

Great that makes sense,  thanks a lot for your help and advice on the sanity check. 

Many thanks for this very useful tool.
Best,
Joe
