### ISSUE TITLE
question slice ordering

### ISSUE THREAD

**Issue by SanRut** [CMRR-C2P/MB#264]
Dear,

The slice ordering I obtain with the MB sequence does not correspond to the slice ordering I was expecting based on the reference below, and  I am wondering what could cause the discrepancy.  

https://wiki.humanconnectome.org/download/attachments/40534057/CMRR_MB_Slice_Order.pdf?version=2&modificationDate=1386950067494&api=v2

We have collected 48 slices with MB =2, thus having 24 shots. Following the algorithm described in the above reference the n-increment is 11.  Using imaging numbering feet to head and 0 index for the first slice I was expecting the following slice ordering:
[0-24], [11-35], [22-46], **[1-25], [12-36]** etc. 

but the MosiacRefAcqTimes has the following order:
[0-24], [11-35], [22-46], **[9-33], [20-44]** 

Could you explain the difference? 

Also the ordering of the SBRef scan is ascending NOT interleaved. Where is this difference coming from? 

Thank you for your reply and best wishes, Sanne

**Comment by swrieger** [comment]
Hi Sanne,

I have a recollection of a bug where the slice acquisition times in the dicom header were erroneous in the first image of each time series. Maybe that's been fixed in the meantime, but it would be easy to check if that's all it is - just pick a different image and see if the slice times look different.

Cheers
Seb

**Comment by SanRut** [comment]
Hello Seb,

Thank you for your prompt reply, it is the same for other slices. I also had seen this and checked it before. 

Best wishes, Sanne

**Comment by joaovduarte** [comment]
I have the same issue.

I acquired data with the CMRR multiband sequence in a 3T Siemens Prisma fit scanner, with:
. TR = 1 sec
. SMS factor = 6
. 72 slices
. number of shots = 12

Following the pseudo-code described in the mentioned document, for even number of shots I get Nincrement = 5, and accordingly the slice ordering I was expecting is:
[0-12-...], [5-17-...], [10-22-...], **[1-13-...], [6-18-...], [11-23-...], [2-14-...], [7-19-...], [3-15-...], [8-20-...], [4-16-...], [9-21-...]**

but the MosaicRefAcqTimes, read directly from the dicom files, has the following order:
[0-12-...], [5-17-...], [10-22-...], **[3-15-...], [8-20-...], [1-13-...], [6-18-...], [11-23-...], [4-16-...], [9-21-...], [2-14-...], [7-19-...]**

I am wondering what could cause the discrepancy, and what is the rule to actually create the order of the slices (both in this real example and in the examples in the document)?

Is the document updated and correct?
https://wiki.humanconnectome.org/download/attachments/40534057/CMRR_MB_Slice_Order.pdf?version=2&modificationDate=1386950067494&api=v2

If so, what does the last sentence mean "_**Known Bug**: The DICOM acquisition time parameters are incorrect for the first MB repetition._" ?
Is this bug fixed? Because I don't see different times between the first MB repetition and any of the other shots.
One thing I do see is that the slice time is somehow slightly lower than TR/number of shots. In my case, 1000/12 = 83.33 msec, but the time in the dicom files is 82.50 msec per shot, which means the acquisition of the 72 slices after 982.50 msec, and not 1000 msec (the TR). Does this make sense?

Thank you in advance for your help.
Best,
João

**Comment by eauerbach** [comment]
Well, that document is quite old...

The bug with the acquisition times of first MB repetition has been fixed for a long time. Also the SBRef scan is now intentionally always ascending order. These changes are documented in the release notes section of the instructions pdf file that comes with the sequences.

I think the acquisition times are recorded as "ticks", which are multiples of 2.5 ms. So TR/shots will not match the acquisition times exactly due to rounding. Also there is some "dead time" at the end of each TR for the online frequency update, etc. so the acquisition times will not sum up to exactly the TR anyway.

As for the interleaved slice order, looking at the document maybe it isn't entirely clear how the increment works, and it does appear there is an error in the Slices=20, Multiband=2 example.

In the document it shows this, which is correct:
Slices=20, Multiband=2, nshots=10, nincrement=3

But this in the document is not correct:
Slice excitation order: [0,10] - [3,13] - [6,16] - [9,19] - ~~[1,11] - [4,14] - [7,17] - [2,12] - [5,15] - [8,18]~~

It should be this (note the increment is applied to the bolded number—it is not necessarily the first number):
Slice excitation order: [**0**,10] - [**3**,13] - [**6**,16] - [**9**,19] - [2,**12**] - [5,**15**] - [8,**18**] - [**1**,11] - [**4**,14] - [**7**,17]

Hopefully that explains it?
