### ISSUE TITLE
fMRI trigger times mapped onto physio output data

### ISSUE THREAD

**Issue by andrewpapale** [CMRR-C2P/MB#275]
Hi, sorry if this is a basic question, but how do I map the fMRI trigger times onto the physio output?  I'm plotting ECG and want to mark every TR to make sure the timing is accurate.

Thanks,
Andrew Papale, PhD

**Comment by eauerbach** [comment]
Assuming you are using one of the readCMRRPhysio tools, that is what the ACQ trace is for. Just plot the ECG trace against the ACQ trace. The ACQ trace is 1 when there is an acquisition active, 0 otherwise. The traces are all the same length and synchronized so they can be compared directly.

**Comment by andrewpapale** [comment]
Thank you for getting back to me Eddie.  In the comments, it says the unit of time for clock ticks is 2.5ms.  How do I recover the TR?  I would guess it's: 

TR = nanmedian(diff(find(diff(double(physio.ACQ))==1)))*2.5 

but this is giving me 67.5ms which is too fast.  Our expected TR is 635ms.  Any help would be appreciated.

Thanks,
Andrew

**Comment by eauerbach** [comment]
The ACQ trace is generated from the SliceMap values. If you want to make timing calculations it is probably easier to work with the SliceMap values, since the ACQ trace commingles all of the slices and volumes. As described in the code comments, e.g. SliceMap(1:2,1,1) will give you the start and stop times of the acquisition of slice 1, volume 1. To get the TR, you would look at something like SliceMap(1,2,1) - SliceMap(1,1,1): the difference of the start times of the same slice between volumes is TR.

**Comment by andrewpapale** [comment]
TR = []; for iT=2:2000; TR(iT)=(physio.SliceMap(1,iT,1)-physio.SliceMap(1,iT-1,1))*2.5; end.     This gives 635ms.  Thanks!
