### ISSUE TITLE
Reconstruction failure: ChannelMixingMatrix not found

### ISSUE THREAD

**Issue by dpapp86** [CMRR-C2P/MB#308]
Happy new year to everyone, and apologies for starting with a complex issue!

**System specs:**
Prisma scanner, VE11C software version, R017 pre 5 multiband version.

**Issue:**
Some colleagues of mine were scanning using a CMRR sequence, and noticed that the scans were not being reconstructed. After about 15 minutes of this happening, they decided that it is probably not just reconstruction lag, and did a full power cycle of the scanner. After the scanner booted again, the same sequence/protocol worked on a phantom and later in-vivo, and no furher issues were found.

Retro recon of the scans that werent being reconstructed also fails.

**Investigation:**
I looked into the issue using TWIX and the Logviewer. The data in TWIX is two files corresponding to the EPI scan, a big one of 30GB, and a small one of less than 100 MB, and the AdjCoilSens scan. I will call these EPI_big.dat, EPI_small.dat and AdjCoilSense.dat. I suspect this is because this EPI is the single band reference scan. Subsequent fMRI runs only result in one big fMRI file (fMRI_big.dat)

- It does appear that the linking between EPI_big.dat and AdjCoilsens.dat is properly visualised, that is, clicking on EPI_big.dat highlights AdjCoilSens.dat in TWIX.
- Running retro recon on AdjCoilSens.dat results in a green tickmark and no errors in the Logviewer. There is mention of a "ChannelMixingMatrix", with a number corresponding to the MID to AdjCoilSens.dat
- Running retro recon on EPI_big.dat or EPI_small.dat on their own does not work, and the ICE error (as per Logviewer) is:
- <img width="621" alt="image" src="https://user-images.githubusercontent.com/80138067/210904765-b6243795-5f7e-40b9-9391-635df13230e3.png"> (18 is the MID of AdjCoilSens.dat).
- Running retro recon on EPI_big.dat and AdjCoilSens.dat together (shift-selecting them both) results in the same error msg. 
- Running retro recon on fMRI_big.dat, together or separate from AdjCoilSens.dat gives the same error

I looked into the behaviour of retro recon on the scans that did successfully reconstruct (those acquired after the scanner was power cycled), and retro recon works, no ice error msgs are shown in the logviewer, and the retro recon scans appear in the proper directory for the patient.

**Solutions tried:**
- Running Retro Recon on these files after another full power cycle
- Using the AST - Simulations ON flag, as suggested [in this issue.](https://github.com/CMRR-C2P/MB/issues/102#issuecomment-144474096)

**My hunch for what the problem is**
I think that somehow, the connection in the ICE chain that link AdjCoilSens.dat to EPI_big.dat is broken. AdjCoilSens.dat in and of itself can be retro reconed (and the logviewer mentions a ChannelMixingMatrix_MID being created, etc), but something breaks when this Matrix is being linked to, and tries to be read by, the ICE program that reconstructs EPI_big.dat.

Luckily, this seems to be a problem specific to that dataset.

Has anyone encountered something similar? Any guesses as to what this could be? We have saved the TWIX data, so any ideas are more than welcome!

best
Daniel

**Comment by rwmair** [comment]
Hi Daniel,

I not sure about the specific failure of this CMRR-based scan, but have done a bunch of Retro-Recon's (RR's) thru Twix. After RRing the AdjCoilSens.dat file, you need to update the MeasID in the main scan file to reflect the new MeasID of the RR'ed version of AdjCoilSens.dat. That's the link from the main scan file to the AdjCoilSens.dat that seems to be missing in your RR attempts.

If no RR'ing has been done in a while and AdjCoilSens.dat is the first thing you RR, it will generally have (on our system anyway) a new MeasID of 3000001. (Refresh the Twix display after the RR, and check the second column in the main Twix window) Once that has been done, highlight the main scan you want to RR and use the Edit button on the RR panel at the bottom of Twix to open the XBuilder interface for the main scan, and search for ChannelMixingUID. It will have the value of the MeasID of the original AdjCoilSens.dat (maybe 18, in your example above, usually a 3 or 4 digit number). Change it to 3000001, save the file. If PreScanNormalize is on in the original protocol, you need to do the same for CoilSensUID - its right above ChannelMixingUID in XBuilder.  So also change 18 to 3000001 for CoilSensUID if needed. Save the file and close the window, then start the retro-recon of the main scan. This time it should proceed correctly.

As for the two EPI.dat files.... if the scanner throws a stimulation warning or (maybe) a SAR warning prior to starting the scan, this results in a small *.dat file with the same sequence name, that is usually ~ 100 MB. I have always ignored this. The big EPI.dat file should RR with the procedure above. That's the one that has your data.

All that said - just why the reconstructor stopped reconstructing during the original running of the scan is going to be hard to figure out without the log files (or a SaveLog) from the time it happened. It may or may not be an issue specific to R017pre5. However, we did experience that exact problem a lot with CMRR scans on VD13D, and I had to rescue a lot of scans with RR's usually in a limited time-frame because the scanner was always busy. (Often when I was traveling!) Eddie believed it was a Siemens issue with the VD software (which had lots of issues) The problem never returned once we upgraded to VE11C.

Do you mind telling us which institution/location you are at with VE11C and R017pre5. I have one scanner where folks are contemplating this change from R016a, but we're trying to get news of other sites using R017pre5 successfully. There's been very few so far who have made this change on VE11C.

Hope that helps,

Ross

**Comment by dpapp86** [comment]
@rwmair 

You are a lifesaver! Changing the ChannelMixingUID worked.

We are UNF in Montreal, and havent had any issues with CMRR sequences since.

Best

Daniel
