### ISSUE TITLE
turning off sense1 with twix

### ISSUE THREAD

**Issue by MRIDude** [CMRR-C2P/MB#311]
Hello, I have very little experience with twix. I was wondering if it is possible to collect data on a Prisma using CMRR T2* EPI with sense1 on then retro reconstruct the data with sense1 off.  Is this possible and how would I go about doing it.

**Comment by whitecraine** [comment]
At least on VE11C, you will want to edit "iceprogrampara.18" to have value 1 (for no SENSE1), 2 (for SENSE1), 3 (for SENSE1 + SBref). I had an OHBM abstract the effects of SENSE1 on T2* EPI in 2021.  Feel free to contact me (an.vu@ucsf.edu) if you'd like a copy.

**Comment by MRIDude** [comment]
I was wondering how to do the same thing with CMRR dti sequence?

**Comment by eauerbach** [comment]
Very specifically, SENSE1 is controlled by the second bit of YAPS.alICEProgramPara.18. In XBuilder you can click the radio button under the long value to edit in binary, in that case the second digit from the right should be 1 for SENSE1, 0 for no SENSE1. Don't change the other positions since that will change other reconstruction options. (Note that leading zeros are not displayed, so if the starting value is 0 or 1 and you want to enable SENSE1, you would enter 10 or 11.)
