### ISSUE TITLE
R017 prerelease diffusion mode "free" not available

### ISSUE THREAD

**Issue by whitecraine** [CMRR-C2P/MB#320]
After installing the R017 prerelease (on VE12U-AP02) the previously saved diffusion protocols do not open properly saying "Protocol was fixed, Please check setting carefully." and they are "fixed" to the default 1 slice 3.9x3.9x5mm settings. When trying to rebuild the protocols from scratch, I noticed the "free" diffusion mode was not an option. Is it possible the new sequence is looking for the .dvs files somewhere else or is there some other bug?

**Comment by eauerbach** [comment]
You are right, there is a bug in R017pre6 that will prevent setting Free mode; it affects the VE versions but not the XA versions. I will upload a fixed version shortly. Presumably the "fixed" protocols were using Free mode?

The .dvs files are still in `C:\Medcom\MriCustomer\seq\DiffusionVectorSets`; this is consistent with all VD/VE versions (but different from VB versions).

**Comment by eauerbach** [comment]
I uploaded updated sequences for the VE versions which fix the "Free" diffusion mode issue. Only the diffusion sequence changed, so if you prefer you can simply copy the new diffusion sequence .dll and .so files to the customer sequence directory rather than running the full installer (embedded control still must be in update mode). The new sequences have a build date of 25 April 2023 but are still named R017pre6.
