### ISSUE TITLE
Physio and IdeaCmdTool

### ISSUE THREAD

**Issue by mharms** [CMRR-C2P/MB#327]
Given the ongoing issues with the Physio = DICOM option on XA30, a question has arisen about this bit of text in `Multi-Band_C2P_Instructions.pdf`:

> Physio. recording: Control recording of physiological signals (cardiac,
respiration, ECG, external) to text or encoded DICOM files. Text files will be
stored in C:\MedCom\Log\Physio\ on the host computer (MRC). Legacy
uses the classic CPmuSequence/IdeaCmdTool logging facility (this is the
only option available on VAxx/VBxx systems and VD11x; it is known to be
unreliable on VD11x/VD13x/VE11x). DICOM and File use the new online/ICE logging available since VD13A, which is recommended for use
when available.

In particular, what was "unreliable" about the use of IdeaCmdTool on VD/VE, and do you know if that issue is still applicable to XA30?  And was it the direct invocation of physio recording via IdeaCmdTool what was unreliable, or just its invocation within the sequence?

**Comment by BPaton** [comment]
Speaking from personal experience using the IdeaCmdTool on a VE-11 system
recordings would sometimes appear to start and we would get a flatline for
the respiration or peripheral pulse channels. Other times the recording
would be fine and then just stop half way through a scanning
session/recording. Plus the default method records to the same named file,
so if you do not copy out the file after a participant has been scanned the
data will be overwritten.

Thanks.

Bryan.

**Comment by mharms** [comment]
Was that experience with using the `Physio = Legacy` option, or were you experiencing that behavior when invoking physio recording via IdeaCmdTool directly yourself?

**Comment by BPaton** [comment]
Via the cmdtool directly myself. Never used the legacy I I option. I would
assume the issues were the same though given it is the tool/method that is
the issue. Happy to be wrong of course.

Bryan.

**Comment by eauerbach** [comment]
IIRC since VD/VE the legacy option stops after 5 minutes or so. In detail I think it had to do with the way the legacy option tries to log all of the signals, but the system would timeout if some of the signals were missing (e.g. if you were not using the ECG at all it did not like attempting to log it). I did not have an option in the UI to just enable the relevant signals. The manual start/stop with ideacmdtool would work because you could manually turn on only the logs you needed. Or I could be remembering this wrong.

Anyway, I never bothered to dig into it further since the DICOM export was so much better. Of course that is currently not true in XA. But I will work on it, there will be an update in pre7. Follow up with #306
