### ISSUE TITLE
Skipping a series number when MB is used

### ISSUE THREAD

**Issue by xiangruili** [CMRR-C2P/MB#346]
From my limited test, it seems that a MB sequence under our recently-updated XA30 Prisma always skips a series number. For example, if current scan step give Series 9 (and 10 if SBRef is enabled), the next scan step will give Series 11 (or 12 with SBRef). The built-in Siemens SMS sequence won't have this outcome.

This is not a serious issue at all, but it is still better to not skip a number. Users may worry they are missing something (that could be true in some cases) if the series numbers are not continuous.

**Comment by eauerbach** [comment]
This is not true, I have seen the same behavior with the product sequence. The pulse sequence has no real control over how series numbers are assigned, this is handled by the system.

My limited experience has been that a series number is skipped if a new scan is started before the previous scan has finished reconstructing. So if you queue up a few computationally demanding MB/SMS acquisitions one after another you will see the skipped series numbers between them. But if the reconstruction is fast enough (low MB factor, no iPAT, etc.) or if you wait between scans you will not see skipped numbers.

Agreed that it would be nice to never have the skipped numbers, but I can't seem to do anything about it; this will have to be fixed by Siemens at the system level in a service pack or new software version. Maybe it is already fixed in XA31/XA50/XA60, I don't know.

**Comment by xiangruili** [comment]
@eauerbach That makes sense. So the Siemens has known the issue, right? Then we won't bother to bring it up during the XA30 upgrade follow-up two days later. Thanks.

**Comment by mharms** [comment]
It would be worth bringing up with the Siemens rep.  Even if they already know about it, it doesn't hurt for someone else to mention it.

**Comment by xiangruili** [comment]
> It would be worth bringing up with the Siemens rep. Even if they already know about it, it doesn't hurt for someone else to mention it.

Okay, we will mention it anyway. 
I will close this issue, since it is a Siemens issue.
