### ISSUE TITLE
GRE reference scan not working for MBME

### ISSUE THREAD

**Issue by adamnarai** [CMRR-C2P/MB#365]
The GRE reference scan option not working when using GRAPPA in cmrr_mbep2d_bold
The GRE option is not even shown in Dot Cockpit, we can only select it during an exam and then we get an error:
`Sequence error: an internal error occurred in a sequence module.`

Scanner: 3T Prisma @ XA30A
Sequence version: R017 pre9
Sequence details: 2.6 mm iso, 5 echos (12.6, 30.72, 48.82, 66.94, 85.04 ms), MB=4, GRAPPA=2, TR=1700 ms

**Comment by adamnarai** [comment]
Somewhat related question: 

Is there a current recommendation on which of the four available reference scans (Single-shot, Segmented, GRE, FLEET) to use?

**Comment by eauerbach** [comment]
That is a bug...it is fixed in pre10 which should be available soon.

I tend to prefer GRE, but it can be argued whether GRE or FLEET is better. Segmented is highly sensitive to motion so it is generally not recommended (except for phantoms or ex vivo samples perhaps). Single-shot has limited use if you want speed over quality and can live with a limited number of lines (for quick scouts or low reduction factors).
