### ISSUE TITLE
[XA61 sp1] CMRR sequence installation fails

### ISSUE THREAD

**Issue by merbtue** [CMRR-C2P/MB#377]
We tryed to install the CMRR sequence to our Avanto_fit with XA61 sp1 (Numaris/X VA61A-08QE). But the installer gives the message, that it could not determine the version from gre.dll. The answer from Siemens was, that obviously the CMRR sequence/installer is not for sp1. I used Release R017pre9 for XA61A from 21-May-2024. Can you provide a version for XA61 sp1?
Thanks, 
Michael

**Comment by rwmair** [comment]
For reasons best known to Siemens, there are apparently multiple versions of IDEA for XA61. The CMRR sequence is derived from the CimaX version, while it seems Sola/Altea/Skyrafit/Avantofit have a different version. It might be a binary incompatibility between the IDEA versions for different scanner models, rather than an issue with SP01 specifically.

**Comment by merbtue** [comment]
Thank you for this information. So I have to change my question: Can you provide a version for XA61 Avanto_fit?

**Comment by eauerbach** [comment]
I am working on a version for XA61-SP1
duplicate of #382
