### ISSUE TITLE
Improved physiological data recording

### ISSUE THREAD

**Issue by eauerbach** [CMRR-C2P/MB#46]
Integrate the more reliable/convenient physiological data logging capability similar to WIP 840 (VD13A and newer only).

**Comment by TimmWetzel** [comment]
Improved physiological logging would be highly appreciated! We have been testing this feature with WIP883A, and some of our projects would greatly benefit from combining it with multiband imaging.

**Comment by mmachizawa** [comment]
We have recently installed your Multiband (MB) EPI sequence. As you may know, the MB has an option to collect (and extract) PMU data (i.e., pulse, resp, ecg, etc). We have recently started collecting PMU data; however, we encountered to an issue that we would like to have your advice on.

The problem is, the PMU logging somehow automatically stops recording during the EPI scan at around 5 minutes. This error persists when we use the IDEAcmdTool's PMU logging option as well. It can, however, logs normally only when "simulating" the PMU data from the IDEAcmdTool (in this case under simulation, the PMU data are successfully recorded over 5 mins). 

I have played around changing parameters or settings but with no success to date. It stops at around 5 mins automatically, which limits our PMU recording on sequences/experimental block longer than 5 min. 

It would be grateful if any of you have any hint to resolve this issue.
Best wishes,
Maro Machizawa

**Comment by mmachizawa** [comment]
Forgot to mention on the above inquiry, we use Siemens VD13 on Verio scanner.

**Comment by eauerbach** [comment]
There is really nothing I can do to improve the existing logging as far as I know, but I will try to incorporate the new style of online/ICE logging (cf. WIP880/883) into the VD13A and newer versions going forward. This should address the start/stop issues.

**Comment by mmachizawa** [comment]
Thank you, eauerbach. I wonder, if anyone using this MB-EPI also experienced the 5-min recording-limit. 

Looking forward to the incorporation. Please keep me posted.

**Comment by LarsVKnudsen** [comment]
We had the same problem with the CMRR MB sequences on a Siemens Prisma. The logging stopped after 5 min when the logging was enabled in the CMRR sequence setup. We have found a working fix, at least on the prisma. The ideacmdtool logging works for us beyond the 5 min threshold but only when the physio-logging option in the sequence setup is disabled and only when you start each modality logging individually. e.g. dont use the menu item 'logHost start all' but use 'start puls' and then start ECG etc. If you use the menu option 'start all' the recording terminates after 5 min.

**Comment by mmachizawa** [comment]
Thank you, Lars V Knudsen, I confirmed on our Verio (VD31) that your method works by start logging individually and stop logging all. We wish a future version of this sequence can do this as well, without a hustle to go into ideacmdtool.

**Comment by eauerbach** [comment]
The new, 100% reliable (?) style of online ICE logging has been tested and is working; it will be included when R013 is released for VD13A/VD13B/VD13C/VD13D/VE11A. The old style of logging will still be optionally available ('Legacy' option).
