### ISSUE TITLE
Significant Banding Artifact in SBRef and MB

### ISSUE THREAD

**Issue by xjqian** [CMRR-C2P/MB#67]
Obvious intensity junctions between MB slice bands are present in SBRef and MB images (both BOLD and DIFF variants). Observed on VD13A Skyra, but may not be limited to VD13A. This regression was introduced between R010 (VD13A commit fd129fc, Dec 13) and R011.

This is a serious regression as the MB images are affected.

**Comment by eauerbach** [comment]
I think perhaps the most relevant change between R010 and R011 is the re-enabling of tx feedback by default on VD13A. It has always been enabled on VD13B/C/D. If the feedback is not working properly with these highly modulated pulses (as we have seen in the past, but were assured was fixed), and if it is either not correcting or is worsening the transmitter linearity, banding is something that could be expected.

Two things I can think of trying. The first thing of course is to turn off the tx feedback to see if it makes things better or worse. On VD13A this is still possible to force with an entry in the %CustomerSeq%\MBAdvancedSettings.ini file:

[SeqDebug]
DisableTxFeedback = 1

The default since R011 is 0 (not disabled = enabled), but 1 will automatically disable the tx feedback for multi-band scans (MB factor > 1). Unfortunately this easy option is not available in VD13D; disabling tx feedback in VD13D requires a percom password.

Another test would be to increase the excitation pulse length. This will drop the peak voltage as well as slow down the modulation, both of which should help if this is indeed the problem.

**Comment by mworden** [comment]
We have found that increasing the excitation pulse length to the maximum does significantly reduce the banding artifact.  Is there any potential negative consequence to doing so?  If not, why not have it always default to the maximum?

**Comment by eauerbach** [comment]
If the RF waveform is distorted, one of the possible consequences is that you will see this kind of artifact. If you have a high multi-band factor and/or a large frequency shift between the bands (large slice FoV), the peak voltage of the pulse will be high and the waveform will be very highly modulated. Both of these make the pulse more difficult to produce in hardware and leave you vulnerable to distortion.

Increasing the length of the pulse can help in a few ways. It reduces the peak voltage of the pulse, which will help if you are having RF amplifier issues (nonlinearity or distortion at high power). It reduces the total bandwidth of the pulse, which could help if the transmitter has a bandwidth limitation (you would likely see this as a shading of the outer bands). Also, there is a hardware limitation on the number of sample points that can be used for a single RF waveform (8192). In the current version of the sequences I am basically always generating the pulses at 1 us per sample up to 8192 us total duration; so as it turns out, all else being equal, the further away you are from 8192 us duration, the less optimally represented the waveform is. I personally never saw a case where this was a noticeable problem, but maybe this could be improved in the future.

The downsides are that since longer pulses have lower bandwidth you will have more signal loss due to B0 inhomogeneity, and of course longer pulses mean longer TE/TR. So the choice is left to the user.
