### ISSUE TITLE
Major striping artifact visible on activation maps

### ISSUE THREAD

**Issue by alexis-oren** [CMRR-C2P/MB#85]
Hi,

We are using release 10b and 11 of the MB sequence on a Siemens Trio using a 32 channel coil.

After performing GLMs we can see alternating lines of positivity and negativity in the statistical activation maps, particularly when selecting contrasts containing relatively few events. E.g.

![artifact_1](https://cloud.githubusercontent.com/assets/10267968/5523068/485b0b60-89cc-11e4-890c-f7a4bc3079c8.png)

They can be easily seen by lowering the statistical threshold and also appear at the group level.

This is what a contrast on the FMRs looks like:

![artifact_2](https://cloud.githubusercontent.com/assets/10267968/5523267/c1391e9e-89ce-11e4-8ae2-e6ed82a566e1.png)

We took VOIs from some of the stripes and plotted time courses which show differences in baseline activity over blue and orange stripes.

What is strange is that when viewing the FMRs /VTCs we don't see these stripes at all.

Any ideas?

**Comment by xjqian** [comment]
This is due to the known MB-EPI sensitivity to motion and these slice correlated artifacts can typically been observed from, and fortunately also can be cleaned-up by ICA analyses. Please see the following reference for details:

Kelly et.al. An assessment of motion artefacts in multi band EPI for high spatial and temporal resolution resting state FMRI,  Proc. Intl. Soc. Mag. Reson. Med. 21 (2013)  pg 3275

FSL ICA-FIX:   http://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FIX    and the references on that page.

Please feel free to close this bug report if the above addresses your question.
