### ISSUE TITLE
MB offline recon intermittent failure

### ISSUE THREAD

**Issue by gbook** [CMRR-C2P/MB#95]
We've been running the remote reconstruction setup for a few months, and most of the time it works great. It has a GeForce 560 card in it, which is not too powerful, but so far its been working to reduce recon time. Now we're noticing an occasional remote reconstruction failure. It's only happened a couple of times, but when it happens, the whole recon process stops and prevents any series from being reconstructed until I kill the recon process on the recon machine and restart it.

Could it be a bad graphics card, or are there any logs I can check?

**Comment by eauerbach** [comment]
If the remote process is hanging, then knowing nothing else I would first blame the GeForce card. In principle it should work, but the difference between GeForce and Quadro/Tesla is supposed to be stability vs. the absolute maximum performance, which is why I only recommend Tesla. The Quadro/Tesla cards have ECC RAM, higher binned chips (sometimes underclocked), and more stable drivers...yes the cost/performance ratio is much higher, but it is nothing compared to the cost of scan time and IMO isn't worth the potential trouble.

**Comment by gbook** [comment]
That's what we suspected too, we'll try a Quadro card
